### ISSUE TITLE
Multi-targeting AutoMapper and .NET Framework 4.8

### ISSUE THREAD

**Issue by InteXX** [Karql/xUnitMultiTargetIssue#1]
Hi @Karql, pardon my off-topic post here; I didn't know how else to contact you.

I read with great interest your reply here:

https://github.com/AutoMapper/AutoMapper/discussions/3873#discussion-3837209

I'm very curious as to how you've managed the multi-targeting you describe. I'm a newcomer to the idea and I'm running into all kinds of dead-ends.

The best I've been able to accomplish so far is to create an assembly targeting both 2.0 and 2.1 that contains some AutoMapper 11.0.1 code—I had to wrap it in compiler directives to get it to build—and then reference that from my 4.8 assembly. It builds and runs, but `AutoMapper.Map()` returns null (because the non-2.1 code execution was excluded by the compiler directives).

How are you pulling this off?

**Comment by Karql** [comment]
Hi @InteXX!

> I didn't know how else to contact you.

I didn't even know my mail was hidden 😉 I have fixed it.

> How are you pulling this off?

More or less in the same way. For my needs I targeting `net472` and `net60`.

Library csproj:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net6.0</TargetFrameworks>
    <TargetFramework Condition="'$(OS)' != 'Windows_NT'">net6.0</TargetFramework>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net6.0'">
    <DefineConstants>NET</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net472'">
    <DefineConstants>NETFULL</DefineConstants>
  </PropertyGroup>

...

  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="AutoMapper" Version="11.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net472'">
    <PackageReference Include="AutoMapper" Version="10.1.1" />
  </ItemGroup>  
</Project>
```

I have `NET` and `NETFULL` constants but don't use them for `AutoMapper`.

Simplified app examples:

ASP.NET Core (`net6` and `Autofac`):
```c#
services.AddAutoMapper(cfg =>
{
    cfg.AddProfile<MappingProfile>();
});
```

ASP.NET MVC (`net472` and `Ninject):
```c#
kernel.BindIfNotExists<AutoMapper.MapperConfiguration>(bind => bind.ToConstant(
    new AutoMapper.MapperConfiguration(cfg => {
        cfg.AddProfile<MappingProfile>()
    })
));

kernel.BindIfNotExists<AutoMapper.IMapper>(bind => bind.ToMethod(ctx =>
{
    var config = ctx.Kernel.Get<AutoMapper.MapperConfiguration>();

    return config.CreateMapper(); ;
}).InRequestScope());
```

In real use I have interface:
```c#
using AutoMapper;

namespace Common.Utils.Reflection.Abstract
{
    public interface ICustomAutoMapperConfig : IOrdered
    {
        void RegisterMappings(IMapperConfigurationExpression cfg);
    }
}
```

in the shared library there are configurations like:
```c#
public class AutoMapperConfiguration : ICustomAutoMapperConfig
{
    public int OrderId => CustomAutoMapperConfigOrder.CustomOrderId;

    public void RegisterMappings(IMapperConfigurationExpression cfg)
    {
        cfg.AddProfile<MappingProfile>();
    }
}

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<TradeTermApiModel, ImportTradeTermModel>();
    }
}
```

and then registration looks like:
```c#
protected virtual void ConfigureAutoMapper(IServiceCollection services)
{
    services.AddAutoMapper(ConfigureAutoMapperAction);
}

protected virtual void ConfigureAutoMapperAction(IMapperConfigurationExpression cfg)
{
    ImplementationResolver.CallEach<ICustomAutoMapperConfig>(x => x.RegisterMappings(cfg));
}
```

Best regards,
Mateusz

**Comment by InteXX** [comment]
Aha. I believe I get it now.

This seems to be the winning clue:

```
<ItemGroup Condition=" '$(TargetFramework)' == 'net6.0'">
  <PackageReference Include="AutoMapper" Version="11.0.0" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'net472'">
  <PackageReference Include="AutoMapper" Version="10.1.1" />
</ItemGroup>
```

Apparently my problems stem from trying to get 4.8 code to run against a 2.1 assembly. I think I see now that that just ain't gonna happen!

If I'm right, this is turning out to be easier than I was expecting. Here's my latest understanding of multi-targeting:

1. Add your monikers to the project file
2. Demarcate your code according to the resulting compiler directives (I don't see any of that above, but I imagine you must have some)
3. Run and enjoy

Is that it in a nutshell, other than some other syntactic sugar here and there?

**Comment by Karql** [comment]
> Apparently my problems stem from trying to get 4.8 code to run against a 2.1 assembly. I think I see now that that just ain't gonna happen!

Yes `netstandard2.1` is not supported  by `.NET Framework` https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-1

Therefor I targeting `net6.0`.

> Demarcate your code according to the resulting compiler directives (I don't see any of that above, but I imagine you must have some)

Like I wrote for `AutoMapper` purposes I don't use compiler directives but I attached them as example 😉

IMO it's better and easier to not use multi targeting.

I have to use it in case of legacy code.
I have old project in ASP.NET Mvc with some cool business logic libraries.
I wanted to use these libraries in new project in ASP.NET Core.
Old project is still under development so I could not migrate libraries to just targeting `net6.0`.

Compiler directives I use very very little.
At the begining they were useful e.g. for `SqlClient`.
New project uses `Microsoft.Data.SqlClient` but old one used `System.Data.SqlClient`.
API is more or less the same so compiler directives were used for using stamtens.

Now old project has been migrated to use `EF Core` so compiler directives have been removed.

**Comment by InteXX** [comment]
> Like I wrote for AutoMapper purposes I don't use compiler directives but I attached them as example

Hm, now I'm lost again.

To tell you the truth, I wasn't able to understand your code examples. I guess I'd have to see them in the context of a full class or project in order to figure out how the pieces fit together. You probably don't have time to put that together, so that's OK. I'll get there 🙂

But if you're not using directives, how are you getting your code to build? There's some code there that looks like it's specific to AutoMapper 11, which when I tried to do that was giving my compiler fits.

**Comment by Karql** [comment]
By compiler directives I mean conditions in `.cs` files like e.g. for [MoreLINQ](https://github.com/morelinq/MoreLINQ)

```c#
using static MoreLinq.Extensions.ForEachExtension;
#if NETFULL
using static MoreLinq.Extensions.DistinctByExtension;
#endif
using other.using;

namespace Some.Namespace
{
    public class PromotionBenefitLogic : IPromotionBenefitLogic
    {
        public List<PromotionProduct> GetProductListFromBenefits(PromotionAExtended promotion, IEnumerable<PromotionProduct> orderedProductList)
        {
            var benefitProductList = sampleRepo.GetBenefits(parameters);

            return benefitProductList.DistinctBy(x => x.prdId).ToList();
        }
    }
}
```

`net6.0` has already implemented `DistinctBy` in `System.Linq` so here is compiler directive to only add using for `net472`.

For `AutoMapper` I have only conditions in `.csproj` for version. 
In that moment API is the same so there is no conditions in code.

**Comment by InteXX** [comment]
> By compiler directives I mean conditions in .cs files

Right, got that.

> In that moment API is the same so there is no conditions in code

Aha. That makes all the difference. So if there _were_ variations in the new API, you'd have no choice but to use them. Correct?

**Comment by Karql** [comment]
> So if there were variations in the new API, you'd have no choice but to use them. Correct?

If you need something from the new API then yes.

**Comment by InteXX** [comment]
Got it. I believe I understand what's going on now.

Thanks!
